// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/ferocious-space/eveapi/models"
)

// GetCharactersCharacterIDSkillsReader is a Reader for the GetCharactersCharacterIDSkills structure.
type GetCharactersCharacterIDSkillsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCharactersCharacterIDSkillsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCharactersCharacterIDSkillsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewGetCharactersCharacterIDSkillsNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewGetCharactersCharacterIDSkillsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetCharactersCharacterIDSkillsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetCharactersCharacterIDSkillsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 420:
		result := NewGetCharactersCharacterIDSkillsEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCharactersCharacterIDSkillsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetCharactersCharacterIDSkillsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetCharactersCharacterIDSkillsGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v4/characters/{character_id}/skills/] get_characters_character_id_skills", response, response.Code())
	}
}

// NewGetCharactersCharacterIDSkillsOK creates a GetCharactersCharacterIDSkillsOK with default headers values
func NewGetCharactersCharacterIDSkillsOK() *GetCharactersCharacterIDSkillsOK {
	return &GetCharactersCharacterIDSkillsOK{}
}

/*
GetCharactersCharacterIDSkillsOK describes a response with status code 200, with default header values.

Known skills for the character
*/
type GetCharactersCharacterIDSkillsOK struct {

	/* The caching mechanism used
	 */
	CacheControl string

	/* RFC7232 compliant entity tag
	 */
	ETag string

	/* RFC7231 formatted datetime string
	 */
	Expires string

	/* RFC7231 formatted datetime string
	 */
	LastModified string

	Payload *GetCharactersCharacterIDSkillsOKBody
}

// IsSuccess returns true when this get characters character Id skills o k response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get characters character Id skills o k response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id skills o k response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id skills o k response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id skills o k response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get characters character Id skills o k response
func (o *GetCharactersCharacterIDSkillsOK) Code() int {
	return 200
}

func (o *GetCharactersCharacterIDSkillsOK) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsOK  %+v", 200, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsOK) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsOK  %+v", 200, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsOK) GetPayload() *GetCharactersCharacterIDSkillsOKBody {
	return o.Payload
}

func (o *GetCharactersCharacterIDSkillsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Cache-Control
	hdrCacheControl := response.GetHeader("Cache-Control")

	if hdrCacheControl != "" {
		o.CacheControl = hdrCacheControl
	}

	// hydrates response header ETag
	hdrETag := response.GetHeader("ETag")

	if hdrETag != "" {
		o.ETag = hdrETag
	}

	// hydrates response header Expires
	hdrExpires := response.GetHeader("Expires")

	if hdrExpires != "" {
		o.Expires = hdrExpires
	}

	// hydrates response header Last-Modified
	hdrLastModified := response.GetHeader("Last-Modified")

	if hdrLastModified != "" {
		o.LastModified = hdrLastModified
	}

	o.Payload = new(GetCharactersCharacterIDSkillsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDSkillsNotModified creates a GetCharactersCharacterIDSkillsNotModified with default headers values
func NewGetCharactersCharacterIDSkillsNotModified() *GetCharactersCharacterIDSkillsNotModified {
	return &GetCharactersCharacterIDSkillsNotModified{}
}

/*
GetCharactersCharacterIDSkillsNotModified describes a response with status code 304, with default header values.

Not modified
*/
type GetCharactersCharacterIDSkillsNotModified struct {

	/* The caching mechanism used
	 */
	CacheControl string

	/* RFC7232 compliant entity tag
	 */
	ETag string

	/* RFC7231 formatted datetime string
	 */
	Expires string

	/* RFC7231 formatted datetime string
	 */
	LastModified string
}

// IsSuccess returns true when this get characters character Id skills not modified response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsNotModified) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id skills not modified response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsNotModified) IsRedirect() bool {
	return true
}

// IsClientError returns true when this get characters character Id skills not modified response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsNotModified) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id skills not modified response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsNotModified) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id skills not modified response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsNotModified) IsCode(code int) bool {
	return code == 304
}

// Code gets the status code for the get characters character Id skills not modified response
func (o *GetCharactersCharacterIDSkillsNotModified) Code() int {
	return 304
}

func (o *GetCharactersCharacterIDSkillsNotModified) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsNotModified ", 304)
}

func (o *GetCharactersCharacterIDSkillsNotModified) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsNotModified ", 304)
}

func (o *GetCharactersCharacterIDSkillsNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Cache-Control
	hdrCacheControl := response.GetHeader("Cache-Control")

	if hdrCacheControl != "" {
		o.CacheControl = hdrCacheControl
	}

	// hydrates response header ETag
	hdrETag := response.GetHeader("ETag")

	if hdrETag != "" {
		o.ETag = hdrETag
	}

	// hydrates response header Expires
	hdrExpires := response.GetHeader("Expires")

	if hdrExpires != "" {
		o.Expires = hdrExpires
	}

	// hydrates response header Last-Modified
	hdrLastModified := response.GetHeader("Last-Modified")

	if hdrLastModified != "" {
		o.LastModified = hdrLastModified
	}

	return nil
}

// NewGetCharactersCharacterIDSkillsBadRequest creates a GetCharactersCharacterIDSkillsBadRequest with default headers values
func NewGetCharactersCharacterIDSkillsBadRequest() *GetCharactersCharacterIDSkillsBadRequest {
	return &GetCharactersCharacterIDSkillsBadRequest{}
}

/*
GetCharactersCharacterIDSkillsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetCharactersCharacterIDSkillsBadRequest struct {
	Payload *models.BadRequest
}

// IsSuccess returns true when this get characters character Id skills bad request response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id skills bad request response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id skills bad request response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id skills bad request response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id skills bad request response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get characters character Id skills bad request response
func (o *GetCharactersCharacterIDSkillsBadRequest) Code() int {
	return 400
}

func (o *GetCharactersCharacterIDSkillsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsBadRequest  %+v", 400, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsBadRequest) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsBadRequest  %+v", 400, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsBadRequest) GetPayload() *models.BadRequest {
	return o.Payload
}

func (o *GetCharactersCharacterIDSkillsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDSkillsUnauthorized creates a GetCharactersCharacterIDSkillsUnauthorized with default headers values
func NewGetCharactersCharacterIDSkillsUnauthorized() *GetCharactersCharacterIDSkillsUnauthorized {
	return &GetCharactersCharacterIDSkillsUnauthorized{}
}

/*
GetCharactersCharacterIDSkillsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetCharactersCharacterIDSkillsUnauthorized struct {
	Payload *models.Unauthorized
}

// IsSuccess returns true when this get characters character Id skills unauthorized response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id skills unauthorized response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id skills unauthorized response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id skills unauthorized response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id skills unauthorized response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get characters character Id skills unauthorized response
func (o *GetCharactersCharacterIDSkillsUnauthorized) Code() int {
	return 401
}

func (o *GetCharactersCharacterIDSkillsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsUnauthorized) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *GetCharactersCharacterIDSkillsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDSkillsForbidden creates a GetCharactersCharacterIDSkillsForbidden with default headers values
func NewGetCharactersCharacterIDSkillsForbidden() *GetCharactersCharacterIDSkillsForbidden {
	return &GetCharactersCharacterIDSkillsForbidden{}
}

/*
GetCharactersCharacterIDSkillsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetCharactersCharacterIDSkillsForbidden struct {
	Payload *models.Forbidden
}

// IsSuccess returns true when this get characters character Id skills forbidden response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id skills forbidden response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id skills forbidden response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id skills forbidden response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id skills forbidden response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get characters character Id skills forbidden response
func (o *GetCharactersCharacterIDSkillsForbidden) Code() int {
	return 403
}

func (o *GetCharactersCharacterIDSkillsForbidden) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsForbidden  %+v", 403, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsForbidden) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsForbidden  %+v", 403, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *GetCharactersCharacterIDSkillsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDSkillsEnhanceYourCalm creates a GetCharactersCharacterIDSkillsEnhanceYourCalm with default headers values
func NewGetCharactersCharacterIDSkillsEnhanceYourCalm() *GetCharactersCharacterIDSkillsEnhanceYourCalm {
	return &GetCharactersCharacterIDSkillsEnhanceYourCalm{}
}

/*
GetCharactersCharacterIDSkillsEnhanceYourCalm describes a response with status code 420, with default header values.

Error limited
*/
type GetCharactersCharacterIDSkillsEnhanceYourCalm struct {
	Payload *models.ErrorLimited
}

// IsSuccess returns true when this get characters character Id skills enhance your calm response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id skills enhance your calm response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id skills enhance your calm response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id skills enhance your calm response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id skills enhance your calm response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) IsCode(code int) bool {
	return code == 420
}

// Code gets the status code for the get characters character Id skills enhance your calm response
func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) Code() int {
	return 420
}

func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) GetPayload() *models.ErrorLimited {
	return o.Payload
}

func (o *GetCharactersCharacterIDSkillsEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorLimited)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDSkillsInternalServerError creates a GetCharactersCharacterIDSkillsInternalServerError with default headers values
func NewGetCharactersCharacterIDSkillsInternalServerError() *GetCharactersCharacterIDSkillsInternalServerError {
	return &GetCharactersCharacterIDSkillsInternalServerError{}
}

/*
GetCharactersCharacterIDSkillsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetCharactersCharacterIDSkillsInternalServerError struct {
	Payload *models.InternalServerError
}

// IsSuccess returns true when this get characters character Id skills internal server error response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id skills internal server error response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id skills internal server error response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id skills internal server error response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get characters character Id skills internal server error response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get characters character Id skills internal server error response
func (o *GetCharactersCharacterIDSkillsInternalServerError) Code() int {
	return 500
}

func (o *GetCharactersCharacterIDSkillsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsInternalServerError) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsInternalServerError) GetPayload() *models.InternalServerError {
	return o.Payload
}

func (o *GetCharactersCharacterIDSkillsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDSkillsServiceUnavailable creates a GetCharactersCharacterIDSkillsServiceUnavailable with default headers values
func NewGetCharactersCharacterIDSkillsServiceUnavailable() *GetCharactersCharacterIDSkillsServiceUnavailable {
	return &GetCharactersCharacterIDSkillsServiceUnavailable{}
}

/*
GetCharactersCharacterIDSkillsServiceUnavailable describes a response with status code 503, with default header values.

Service unavailable
*/
type GetCharactersCharacterIDSkillsServiceUnavailable struct {
	Payload *models.ServiceUnavailable
}

// IsSuccess returns true when this get characters character Id skills service unavailable response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id skills service unavailable response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id skills service unavailable response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id skills service unavailable response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get characters character Id skills service unavailable response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get characters character Id skills service unavailable response
func (o *GetCharactersCharacterIDSkillsServiceUnavailable) Code() int {
	return 503
}

func (o *GetCharactersCharacterIDSkillsServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsServiceUnavailable) GetPayload() *models.ServiceUnavailable {
	return o.Payload
}

func (o *GetCharactersCharacterIDSkillsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDSkillsGatewayTimeout creates a GetCharactersCharacterIDSkillsGatewayTimeout with default headers values
func NewGetCharactersCharacterIDSkillsGatewayTimeout() *GetCharactersCharacterIDSkillsGatewayTimeout {
	return &GetCharactersCharacterIDSkillsGatewayTimeout{}
}

/*
GetCharactersCharacterIDSkillsGatewayTimeout describes a response with status code 504, with default header values.

Gateway timeout
*/
type GetCharactersCharacterIDSkillsGatewayTimeout struct {
	Payload *models.GatewayTimeout
}

// IsSuccess returns true when this get characters character Id skills gateway timeout response has a 2xx status code
func (o *GetCharactersCharacterIDSkillsGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id skills gateway timeout response has a 3xx status code
func (o *GetCharactersCharacterIDSkillsGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id skills gateway timeout response has a 4xx status code
func (o *GetCharactersCharacterIDSkillsGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id skills gateway timeout response has a 5xx status code
func (o *GetCharactersCharacterIDSkillsGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this get characters character Id skills gateway timeout response a status code equal to that given
func (o *GetCharactersCharacterIDSkillsGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the get characters character Id skills gateway timeout response
func (o *GetCharactersCharacterIDSkillsGatewayTimeout) Code() int {
	return 504
}

func (o *GetCharactersCharacterIDSkillsGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsGatewayTimeout) String() string {
	return fmt.Sprintf("[GET /v4/characters/{character_id}/skills/][%d] getCharactersCharacterIdSkillsGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetCharactersCharacterIDSkillsGatewayTimeout) GetPayload() *models.GatewayTimeout {
	return o.Payload
}

func (o *GetCharactersCharacterIDSkillsGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayTimeout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetCharactersCharacterIDSkillsOKBody get_characters_character_id_skills_ok
//
// 200 ok object
swagger:model GetCharactersCharacterIDSkillsOKBody
*/
type GetCharactersCharacterIDSkillsOKBody struct {

	// get_characters_character_id_skills_skills
	//
	// skills array
	// Required: true
	// Max Items: 1000
	Skills []*GetCharactersCharacterIDSkillsOKBodySkillsItems0 `json:"skills"`

	// get_characters_character_id_skills_total_sp
	//
	// total_sp integer
	// Required: true
	TotalSp *int64 `json:"total_sp"`

	// get_characters_character_id_skills_unallocated_sp
	//
	// Skill points available to be assigned
	UnallocatedSp int32 `json:"unallocated_sp,omitempty"`
}

// Validate validates this get characters character ID skills o k body
func (o *GetCharactersCharacterIDSkillsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSkills(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTotalSp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDSkillsOKBody) validateSkills(formats strfmt.Registry) error {

	if err := validate.Required("getCharactersCharacterIdSkillsOK"+"."+"skills", "body", o.Skills); err != nil {
		return err
	}

	iSkillsSize := int64(len(o.Skills))

	if err := validate.MaxItems("getCharactersCharacterIdSkillsOK"+"."+"skills", "body", iSkillsSize, 1000); err != nil {
		return err
	}

	for i := 0; i < len(o.Skills); i++ {
		if swag.IsZero(o.Skills[i]) { // not required
			continue
		}

		if o.Skills[i] != nil {
			if err := o.Skills[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCharactersCharacterIdSkillsOK" + "." + "skills" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getCharactersCharacterIdSkillsOK" + "." + "skills" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCharactersCharacterIDSkillsOKBody) validateTotalSp(formats strfmt.Registry) error {

	if err := validate.Required("getCharactersCharacterIdSkillsOK"+"."+"total_sp", "body", o.TotalSp); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get characters character ID skills o k body based on the context it is used
func (o *GetCharactersCharacterIDSkillsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSkills(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDSkillsOKBody) contextValidateSkills(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Skills); i++ {

		if o.Skills[i] != nil {

			if swag.IsZero(o.Skills[i]) { // not required
				return nil
			}

			if err := o.Skills[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCharactersCharacterIdSkillsOK" + "." + "skills" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getCharactersCharacterIdSkillsOK" + "." + "skills" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDSkillsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDSkillsOKBody) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDSkillsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDSkillsOKBodySkillsItems0 get_characters_character_id_skills_skill
//
// skill object
swagger:model GetCharactersCharacterIDSkillsOKBodySkillsItems0
*/
type GetCharactersCharacterIDSkillsOKBodySkillsItems0 struct {

	// get_characters_character_id_skills_active_skill_level
	//
	// active_skill_level integer
	// Required: true
	ActiveSkillLevel *int32 `json:"active_skill_level"`

	// get_characters_character_id_skills_skill_id
	//
	// skill_id integer
	// Required: true
	SkillID *int32 `json:"skill_id"`

	// get_characters_character_id_skills_skillpoints_in_skill
	//
	// skillpoints_in_skill integer
	// Required: true
	SkillpointsInSkill *int64 `json:"skillpoints_in_skill"`

	// get_characters_character_id_skills_trained_skill_level
	//
	// trained_skill_level integer
	// Required: true
	TrainedSkillLevel *int32 `json:"trained_skill_level"`
}

// Validate validates this get characters character ID skills o k body skills items0
func (o *GetCharactersCharacterIDSkillsOKBodySkillsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateActiveSkillLevel(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSkillID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSkillpointsInSkill(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTrainedSkillLevel(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDSkillsOKBodySkillsItems0) validateActiveSkillLevel(formats strfmt.Registry) error {

	if err := validate.Required("active_skill_level", "body", o.ActiveSkillLevel); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDSkillsOKBodySkillsItems0) validateSkillID(formats strfmt.Registry) error {

	if err := validate.Required("skill_id", "body", o.SkillID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDSkillsOKBodySkillsItems0) validateSkillpointsInSkill(formats strfmt.Registry) error {

	if err := validate.Required("skillpoints_in_skill", "body", o.SkillpointsInSkill); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDSkillsOKBodySkillsItems0) validateTrainedSkillLevel(formats strfmt.Registry) error {

	if err := validate.Required("trained_skill_level", "body", o.TrainedSkillLevel); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get characters character ID skills o k body skills items0 based on context it is used
func (o *GetCharactersCharacterIDSkillsOKBodySkillsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDSkillsOKBodySkillsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDSkillsOKBodySkillsItems0) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDSkillsOKBodySkillsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
