// Code generated by go-swagger; DO NOT EDIT.

package planetary_interaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/ferocious-space/eveapi/models"
)

// GetCharactersCharacterIDPlanetsPlanetIDReader is a Reader for the GetCharactersCharacterIDPlanetsPlanetID structure.
type GetCharactersCharacterIDPlanetsPlanetIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCharactersCharacterIDPlanetsPlanetIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 420:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCharactersCharacterIDPlanetsPlanetIDOK creates a GetCharactersCharacterIDPlanetsPlanetIDOK with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDOK() *GetCharactersCharacterIDPlanetsPlanetIDOK {
	return &GetCharactersCharacterIDPlanetsPlanetIDOK{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOK describes a response with status code 200, with default header values.

Colony layout
*/
type GetCharactersCharacterIDPlanetsPlanetIDOK struct {
	Payload *GetCharactersCharacterIDPlanetsPlanetIDOKBody
}

// IsSuccess returns true when this get characters character Id planets planet Id o k response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get characters character Id planets planet Id o k response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id o k response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id planets planet Id o k response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id planets planet Id o k response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdOK  %+v", 200, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdOK  %+v", 200, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) GetPayload() *GetCharactersCharacterIDPlanetsPlanetIDOKBody {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCharactersCharacterIDPlanetsPlanetIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDPlanetsPlanetIDBadRequest creates a GetCharactersCharacterIDPlanetsPlanetIDBadRequest with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDBadRequest() *GetCharactersCharacterIDPlanetsPlanetIDBadRequest {
	return &GetCharactersCharacterIDPlanetsPlanetIDBadRequest{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetCharactersCharacterIDPlanetsPlanetIDBadRequest struct {
	Payload *models.BadRequest
}

// IsSuccess returns true when this get characters character Id planets planet Id bad request response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id planets planet Id bad request response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id bad request response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id planets planet Id bad request response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id planets planet Id bad request response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) GetPayload() *models.BadRequest {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDPlanetsPlanetIDUnauthorized creates a GetCharactersCharacterIDPlanetsPlanetIDUnauthorized with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDUnauthorized() *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized {
	return &GetCharactersCharacterIDPlanetsPlanetIDUnauthorized{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetCharactersCharacterIDPlanetsPlanetIDUnauthorized struct {
	Payload *models.Unauthorized
}

// IsSuccess returns true when this get characters character Id planets planet Id unauthorized response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id planets planet Id unauthorized response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id unauthorized response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id planets planet Id unauthorized response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id planets planet Id unauthorized response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDPlanetsPlanetIDForbidden creates a GetCharactersCharacterIDPlanetsPlanetIDForbidden with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDForbidden() *GetCharactersCharacterIDPlanetsPlanetIDForbidden {
	return &GetCharactersCharacterIDPlanetsPlanetIDForbidden{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetCharactersCharacterIDPlanetsPlanetIDForbidden struct {
	Payload *models.Forbidden
}

// IsSuccess returns true when this get characters character Id planets planet Id forbidden response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id planets planet Id forbidden response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id forbidden response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id planets planet Id forbidden response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id planets planet Id forbidden response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdForbidden  %+v", 403, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdForbidden  %+v", 403, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDPlanetsPlanetIDNotFound creates a GetCharactersCharacterIDPlanetsPlanetIDNotFound with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDNotFound() *GetCharactersCharacterIDPlanetsPlanetIDNotFound {
	return &GetCharactersCharacterIDPlanetsPlanetIDNotFound{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDNotFound describes a response with status code 404, with default header values.

Colony not found
*/
type GetCharactersCharacterIDPlanetsPlanetIDNotFound struct {
	Payload *GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody
}

// IsSuccess returns true when this get characters character Id planets planet Id not found response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id planets planet Id not found response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id not found response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id planets planet Id not found response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id planets planet Id not found response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdNotFound  %+v", 404, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdNotFound  %+v", 404, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) GetPayload() *GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm creates a GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm() *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm {
	return &GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm describes a response with status code 420, with default header values.

Error limited
*/
type GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm struct {
	Payload *models.ErrorLimited
}

// IsSuccess returns true when this get characters character Id planets planet Id enhance your calm response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id planets planet Id enhance your calm response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id enhance your calm response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) IsClientError() bool {
	return true
}

// IsServerError returns true when this get characters character Id planets planet Id enhance your calm response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) IsServerError() bool {
	return false
}

// IsCode returns true when this get characters character Id planets planet Id enhance your calm response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) IsCode(code int) bool {
	return code == 420
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) GetPayload() *models.ErrorLimited {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorLimited)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDPlanetsPlanetIDInternalServerError creates a GetCharactersCharacterIDPlanetsPlanetIDInternalServerError with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDInternalServerError() *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError {
	return &GetCharactersCharacterIDPlanetsPlanetIDInternalServerError{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetCharactersCharacterIDPlanetsPlanetIDInternalServerError struct {
	Payload *models.InternalServerError
}

// IsSuccess returns true when this get characters character Id planets planet Id internal server error response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id planets planet Id internal server error response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id internal server error response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id planets planet Id internal server error response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get characters character Id planets planet Id internal server error response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) GetPayload() *models.InternalServerError {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable creates a GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable() *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable {
	return &GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable describes a response with status code 503, with default header values.

Service unavailable
*/
type GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable struct {
	Payload *models.ServiceUnavailable
}

// IsSuccess returns true when this get characters character Id planets planet Id service unavailable response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id planets planet Id service unavailable response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id service unavailable response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id planets planet Id service unavailable response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get characters character Id planets planet Id service unavailable response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) GetPayload() *models.ServiceUnavailable {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout creates a GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout() *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout {
	return &GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout{}
}

/*
GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout describes a response with status code 504, with default header values.

Gateway timeout
*/
type GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout struct {
	Payload *models.GatewayTimeout
}

// IsSuccess returns true when this get characters character Id planets planet Id gateway timeout response has a 2xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get characters character Id planets planet Id gateway timeout response has a 3xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get characters character Id planets planet Id gateway timeout response has a 4xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this get characters character Id planets planet Id gateway timeout response has a 5xx status code
func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this get characters character Id planets planet Id gateway timeout response a status code equal to that given
func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) String() string {
	return fmt.Sprintf("[GET /v3/characters/{character_id}/planets/{planet_id}/][%d] getCharactersCharacterIdPlanetsPlanetIdGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) GetPayload() *models.GatewayTimeout {
	return o.Payload
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayTimeout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody get_characters_character_id_planets_planet_id_not_found
//
// Colony not found
swagger:model GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody
*/
type GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody struct {

	// get_characters_character_id_planets_planet_id_error
	//
	// error message
	Error string `json:"error,omitempty"`
}

// Validate validates this get characters character ID planets planet ID not found body
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get characters character ID planets planet ID not found body based on context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOKBody get_characters_character_id_planets_planet_id_ok
//
// 200 ok object
swagger:model GetCharactersCharacterIDPlanetsPlanetIDOKBody
*/
type GetCharactersCharacterIDPlanetsPlanetIDOKBody struct {

	// get_characters_character_id_planets_planet_id_links
	//
	// links array
	// Required: true
	// Max Items: 500
	Links []*GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0 `json:"links"`

	// get_characters_character_id_planets_planet_id_pins
	//
	// pins array
	// Required: true
	// Max Items: 100
	Pins []*GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0 `json:"pins"`

	// get_characters_character_id_planets_planet_id_routes
	//
	// routes array
	// Required: true
	// Max Items: 1000
	Routes []*GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0 `json:"routes"`
}

// Validate validates this get characters character ID planets planet ID o k body
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePins(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRoutes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) validateLinks(formats strfmt.Registry) error {

	if err := validate.Required("getCharactersCharacterIdPlanetsPlanetIdOK"+"."+"links", "body", o.Links); err != nil {
		return err
	}

	iLinksSize := int64(len(o.Links))

	if err := validate.MaxItems("getCharactersCharacterIdPlanetsPlanetIdOK"+"."+"links", "body", iLinksSize, 500); err != nil {
		return err
	}

	for i := 0; i < len(o.Links); i++ {
		if swag.IsZero(o.Links[i]) { // not required
			continue
		}

		if o.Links[i] != nil {
			if err := o.Links[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "links" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "links" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) validatePins(formats strfmt.Registry) error {

	if err := validate.Required("getCharactersCharacterIdPlanetsPlanetIdOK"+"."+"pins", "body", o.Pins); err != nil {
		return err
	}

	iPinsSize := int64(len(o.Pins))

	if err := validate.MaxItems("getCharactersCharacterIdPlanetsPlanetIdOK"+"."+"pins", "body", iPinsSize, 100); err != nil {
		return err
	}

	for i := 0; i < len(o.Pins); i++ {
		if swag.IsZero(o.Pins[i]) { // not required
			continue
		}

		if o.Pins[i] != nil {
			if err := o.Pins[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "pins" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "pins" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) validateRoutes(formats strfmt.Registry) error {

	if err := validate.Required("getCharactersCharacterIdPlanetsPlanetIdOK"+"."+"routes", "body", o.Routes); err != nil {
		return err
	}

	iRoutesSize := int64(len(o.Routes))

	if err := validate.MaxItems("getCharactersCharacterIdPlanetsPlanetIdOK"+"."+"routes", "body", iRoutesSize, 1000); err != nil {
		return err
	}

	for i := 0; i < len(o.Routes); i++ {
		if swag.IsZero(o.Routes[i]) { // not required
			continue
		}

		if o.Routes[i] != nil {
			if err := o.Routes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "routes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "routes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get characters character ID planets planet ID o k body based on the context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidatePins(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateRoutes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Links); i++ {

		if o.Links[i] != nil {
			if err := o.Links[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "links" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "links" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) contextValidatePins(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Pins); i++ {

		if o.Pins[i] != nil {
			if err := o.Pins[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "pins" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "pins" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) contextValidateRoutes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Routes); i++ {

		if o.Routes[i] != nil {
			if err := o.Routes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "routes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getCharactersCharacterIdPlanetsPlanetIdOK" + "." + "routes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0 get_characters_character_id_planets_planet_id_link
//
// link object
swagger:model GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0
*/
type GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0 struct {

	// get_characters_character_id_planets_planet_id_destination_pin_id
	//
	// destination_pin_id integer
	// Required: true
	DestinationPinID *int64 `json:"destination_pin_id"`

	// get_characters_character_id_planets_planet_id_link_level
	//
	// link_level integer
	// Required: true
	// Maximum: 10
	// Minimum: 0
	LinkLevel *int32 `json:"link_level"`

	// get_characters_character_id_planets_planet_id_source_pin_id
	//
	// source_pin_id integer
	// Required: true
	SourcePinID *int64 `json:"source_pin_id"`
}

// Validate validates this get characters character ID planets planet ID o k body links items0
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDestinationPinID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLinkLevel(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSourcePinID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0) validateDestinationPinID(formats strfmt.Registry) error {

	if err := validate.Required("destination_pin_id", "body", o.DestinationPinID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0) validateLinkLevel(formats strfmt.Registry) error {

	if err := validate.Required("link_level", "body", o.LinkLevel); err != nil {
		return err
	}

	if err := validate.MinimumInt("link_level", "body", int64(*o.LinkLevel), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("link_level", "body", int64(*o.LinkLevel), 10, false); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0) validateSourcePinID(formats strfmt.Registry) error {

	if err := validate.Required("source_pin_id", "body", o.SourcePinID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get characters character ID planets planet ID o k body links items0 based on context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDOKBodyLinksItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0 get_characters_character_id_planets_planet_id_pin
//
// pin object
swagger:model GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0
*/
type GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0 struct {

	// get_characters_character_id_planets_planet_id_contents
	//
	// contents array
	// Max Items: 90
	Contents []*GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0 `json:"contents"`

	// get_characters_character_id_planets_planet_id_expiry_time
	//
	// expiry_time string
	// Format: date-time
	ExpiryTime strfmt.DateTime `json:"expiry_time,omitempty"`

	// extractor details
	ExtractorDetails *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails `json:"extractor_details,omitempty"`

	// factory details
	FactoryDetails *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails `json:"factory_details,omitempty"`

	// get_characters_character_id_planets_planet_id_install_time
	//
	// install_time string
	// Format: date-time
	InstallTime strfmt.DateTime `json:"install_time,omitempty"`

	// get_characters_character_id_planets_planet_id_last_cycle_start
	//
	// last_cycle_start string
	// Format: date-time
	LastCycleStart strfmt.DateTime `json:"last_cycle_start,omitempty"`

	// get_characters_character_id_planets_planet_id_latitude
	//
	// latitude number
	// Required: true
	Latitude *float32 `json:"latitude"`

	// get_characters_character_id_planets_planet_id_longitude
	//
	// longitude number
	// Required: true
	Longitude *float32 `json:"longitude"`

	// get_characters_character_id_planets_planet_id_pin_id
	//
	// pin_id integer
	// Required: true
	PinID *int64 `json:"pin_id"`

	// get_characters_character_id_planets_planet_id_schematic_id
	//
	// schematic_id integer
	SchematicID int32 `json:"schematic_id,omitempty"`

	// get_characters_character_id_planets_planet_id_type_id
	//
	// type_id integer
	// Required: true
	TypeID *int32 `json:"type_id"`
}

// Validate validates this get characters character ID planets planet ID o k body pins items0
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContents(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateExpiryTime(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateExtractorDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFactoryDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateInstallTime(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLastCycleStart(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLatitude(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLongitude(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePinID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTypeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateContents(formats strfmt.Registry) error {
	if swag.IsZero(o.Contents) { // not required
		return nil
	}

	iContentsSize := int64(len(o.Contents))

	if err := validate.MaxItems("contents", "body", iContentsSize, 90); err != nil {
		return err
	}

	for i := 0; i < len(o.Contents); i++ {
		if swag.IsZero(o.Contents[i]) { // not required
			continue
		}

		if o.Contents[i] != nil {
			if err := o.Contents[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("contents" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("contents" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateExpiryTime(formats strfmt.Registry) error {
	if swag.IsZero(o.ExpiryTime) { // not required
		return nil
	}

	if err := validate.FormatOf("expiry_time", "body", "date-time", o.ExpiryTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateExtractorDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.ExtractorDetails) { // not required
		return nil
	}

	if o.ExtractorDetails != nil {
		if err := o.ExtractorDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("extractor_details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("extractor_details")
			}
			return err
		}
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateFactoryDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.FactoryDetails) { // not required
		return nil
	}

	if o.FactoryDetails != nil {
		if err := o.FactoryDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("factory_details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("factory_details")
			}
			return err
		}
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateInstallTime(formats strfmt.Registry) error {
	if swag.IsZero(o.InstallTime) { // not required
		return nil
	}

	if err := validate.FormatOf("install_time", "body", "date-time", o.InstallTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateLastCycleStart(formats strfmt.Registry) error {
	if swag.IsZero(o.LastCycleStart) { // not required
		return nil
	}

	if err := validate.FormatOf("last_cycle_start", "body", "date-time", o.LastCycleStart.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateLatitude(formats strfmt.Registry) error {

	if err := validate.Required("latitude", "body", o.Latitude); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateLongitude(formats strfmt.Registry) error {

	if err := validate.Required("longitude", "body", o.Longitude); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validatePinID(formats strfmt.Registry) error {

	if err := validate.Required("pin_id", "body", o.PinID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) validateTypeID(formats strfmt.Registry) error {

	if err := validate.Required("type_id", "body", o.TypeID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get characters character ID planets planet ID o k body pins items0 based on the context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateContents(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateExtractorDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateFactoryDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) contextValidateContents(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Contents); i++ {

		if o.Contents[i] != nil {
			if err := o.Contents[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("contents" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("contents" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) contextValidateExtractorDetails(ctx context.Context, formats strfmt.Registry) error {

	if o.ExtractorDetails != nil {
		if err := o.ExtractorDetails.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("extractor_details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("extractor_details")
			}
			return err
		}
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) contextValidateFactoryDetails(ctx context.Context, formats strfmt.Registry) error {

	if o.FactoryDetails != nil {
		if err := o.FactoryDetails.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("factory_details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("factory_details")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0 get_characters_character_id_planets_planet_id_content
//
// content object
swagger:model GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0
*/
type GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0 struct {

	// get_characters_character_id_planets_planet_id_amount
	//
	// amount integer
	// Required: true
	Amount *int64 `json:"amount"`

	// get_characters_character_id_planets_planet_id_content_type_id
	//
	// type_id integer
	// Required: true
	TypeID *int32 `json:"type_id"`
}

// Validate validates this get characters character ID planets planet ID o k body pins items0 contents items0
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTypeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", o.Amount); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0) validateTypeID(formats strfmt.Registry) error {

	if err := validate.Required("type_id", "body", o.TypeID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get characters character ID planets planet ID o k body pins items0 contents items0 based on context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ContentsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails get_characters_character_id_planets_planet_id_extractor_details
//
// extractor_details object
swagger:model GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails
*/
type GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails struct {

	// get_characters_character_id_planets_planet_id_cycle_time
	//
	// in seconds
	CycleTime int32 `json:"cycle_time,omitempty"`

	// get_characters_character_id_planets_planet_id_head_radius
	//
	// head_radius number
	HeadRadius float32 `json:"head_radius,omitempty"`

	// get_characters_character_id_planets_planet_id_heads
	//
	// heads array
	// Required: true
	// Max Items: 10
	Heads []*GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0 `json:"heads"`

	// get_characters_character_id_planets_planet_id_product_type_id
	//
	// product_type_id integer
	ProductTypeID int32 `json:"product_type_id,omitempty"`

	// get_characters_character_id_planets_planet_id_qty_per_cycle
	//
	// qty_per_cycle integer
	QtyPerCycle int32 `json:"qty_per_cycle,omitempty"`
}

// Validate validates this get characters character ID planets planet ID o k body pins items0 extractor details
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHeads(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails) validateHeads(formats strfmt.Registry) error {

	if err := validate.Required("extractor_details"+"."+"heads", "body", o.Heads); err != nil {
		return err
	}

	iHeadsSize := int64(len(o.Heads))

	if err := validate.MaxItems("extractor_details"+"."+"heads", "body", iHeadsSize, 10); err != nil {
		return err
	}

	for i := 0; i < len(o.Heads); i++ {
		if swag.IsZero(o.Heads[i]) { // not required
			continue
		}

		if o.Heads[i] != nil {
			if err := o.Heads[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("extractor_details" + "." + "heads" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("extractor_details" + "." + "heads" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get characters character ID planets planet ID o k body pins items0 extractor details based on the context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateHeads(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails) contextValidateHeads(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Heads); i++ {

		if o.Heads[i] != nil {
			if err := o.Heads[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("extractor_details" + "." + "heads" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("extractor_details" + "." + "heads" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0 get_characters_character_id_planets_planet_id_head
//
// head object
swagger:model GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0
*/
type GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0 struct {

	// get_characters_character_id_planets_planet_id_head_id
	//
	// head_id integer
	// Required: true
	// Maximum: 9
	// Minimum: 0
	HeadID *int32 `json:"head_id"`

	// get_characters_character_id_planets_planet_id_head_latitude
	//
	// latitude number
	// Required: true
	Latitude *float32 `json:"latitude"`

	// get_characters_character_id_planets_planet_id_head_longitude
	//
	// longitude number
	// Required: true
	Longitude *float32 `json:"longitude"`
}

// Validate validates this get characters character ID planets planet ID o k body pins items0 extractor details heads items0
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHeadID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLatitude(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLongitude(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0) validateHeadID(formats strfmt.Registry) error {

	if err := validate.Required("head_id", "body", o.HeadID); err != nil {
		return err
	}

	if err := validate.MinimumInt("head_id", "body", int64(*o.HeadID), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("head_id", "body", int64(*o.HeadID), 9, false); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0) validateLatitude(formats strfmt.Registry) error {

	if err := validate.Required("latitude", "body", o.Latitude); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0) validateLongitude(formats strfmt.Registry) error {

	if err := validate.Required("longitude", "body", o.Longitude); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get characters character ID planets planet ID o k body pins items0 extractor details heads items0 based on context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0ExtractorDetailsHeadsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails get_characters_character_id_planets_planet_id_factory_details
//
// factory_details object
swagger:model GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails
*/
type GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails struct {

	// get_characters_character_id_planets_planet_id_factory_details_schematic_id
	//
	// schematic_id integer
	// Required: true
	SchematicID *int32 `json:"schematic_id"`
}

// Validate validates this get characters character ID planets planet ID o k body pins items0 factory details
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSchematicID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails) validateSchematicID(formats strfmt.Registry) error {

	if err := validate.Required("factory_details"+"."+"schematic_id", "body", o.SchematicID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get characters character ID planets planet ID o k body pins items0 factory details based on context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDOKBodyPinsItems0FactoryDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0 get_characters_character_id_planets_planet_id_route
//
// route object
swagger:model GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0
*/
type GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0 struct {

	// get_characters_character_id_planets_planet_id_route_content_type_id
	//
	// content_type_id integer
	// Required: true
	ContentTypeID *int32 `json:"content_type_id"`

	// get_characters_character_id_planets_planet_id_route_destination_pin_id
	//
	// destination_pin_id integer
	// Required: true
	DestinationPinID *int64 `json:"destination_pin_id"`

	// get_characters_character_id_planets_planet_id_quantity
	//
	// quantity number
	// Required: true
	Quantity *float32 `json:"quantity"`

	// get_characters_character_id_planets_planet_id_route_id
	//
	// route_id integer
	// Required: true
	RouteID *int64 `json:"route_id"`

	// get_characters_character_id_planets_planet_id_route_source_pin_id
	//
	// source_pin_id integer
	// Required: true
	SourcePinID *int64 `json:"source_pin_id"`

	// get_characters_character_id_planets_planet_id_waypoints
	//
	// list of pin ID waypoints
	// Max Items: 5
	Waypoints []int64 `json:"waypoints"`
}

// Validate validates this get characters character ID planets planet ID o k body routes items0
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContentTypeID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDestinationPinID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRouteID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSourcePinID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateWaypoints(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) validateContentTypeID(formats strfmt.Registry) error {

	if err := validate.Required("content_type_id", "body", o.ContentTypeID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) validateDestinationPinID(formats strfmt.Registry) error {

	if err := validate.Required("destination_pin_id", "body", o.DestinationPinID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", o.Quantity); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) validateRouteID(formats strfmt.Registry) error {

	if err := validate.Required("route_id", "body", o.RouteID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) validateSourcePinID(formats strfmt.Registry) error {

	if err := validate.Required("source_pin_id", "body", o.SourcePinID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) validateWaypoints(formats strfmt.Registry) error {
	if swag.IsZero(o.Waypoints) { // not required
		return nil
	}

	iWaypointsSize := int64(len(o.Waypoints))

	if err := validate.MaxItems("waypoints", "body", iWaypointsSize, 5); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get characters character ID planets planet ID o k body routes items0 based on context it is used
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDPlanetsPlanetIDOKBodyRoutesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
