// Code generated by go-swagger; DO NOT EDIT.

package mail

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ferocious-space/eveapi/models"
)

// DeleteCharactersCharacterIDMailLabelsLabelIDReader is a Reader for the DeleteCharactersCharacterIDMailLabelsLabelID structure.
type DeleteCharactersCharacterIDMailLabelsLabelIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 420:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewDeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDNoContent creates a DeleteCharactersCharacterIDMailLabelsLabelIDNoContent with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDNoContent() *DeleteCharactersCharacterIDMailLabelsLabelIDNoContent {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDNoContent{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDNoContent describes a response with status code 204, with default header values.

Label deleted
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDNoContent struct {
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdNoContent ", 204)
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDBadRequest creates a DeleteCharactersCharacterIDMailLabelsLabelIDBadRequest with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDBadRequest() *DeleteCharactersCharacterIDMailLabelsLabelIDBadRequest {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDBadRequest{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDBadRequest struct {
	Payload *models.BadRequest
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDBadRequest) GetPayload() *models.BadRequest {
	return o.Payload
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized creates a DeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized() *DeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized struct {
	Payload *models.Unauthorized
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDForbidden creates a DeleteCharactersCharacterIDMailLabelsLabelIDForbidden with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDForbidden() *DeleteCharactersCharacterIDMailLabelsLabelIDForbidden {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDForbidden{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDForbidden struct {
	Payload *models.Forbidden
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdForbidden  %+v", 403, o.Payload)
}
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm creates a DeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm() *DeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm describes a response with status code 420, with default header values.

Error limited
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm struct {
	Payload *models.ErrorLimited
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdEnhanceYourCalm  %+v", 420, o.Payload)
}
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm) GetPayload() *models.ErrorLimited {
	return o.Payload
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorLimited)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity creates a DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity() *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity describes a response with status code 422, with default header values.

Default labels cannot be deleted
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity struct {
	Payload *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity) GetPayload() *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody {
	return o.Payload
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError creates a DeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError() *DeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError) GetPayload() *models.InternalServerError {
	return o.Payload
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable creates a DeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable() *DeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable describes a response with status code 503, with default header values.

Service unavailable
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable struct {
	Payload *models.ServiceUnavailable
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdServiceUnavailable  %+v", 503, o.Payload)
}
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable) GetPayload() *models.ServiceUnavailable {
	return o.Payload
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout creates a DeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout with default headers values
func NewDeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout() *DeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout {
	return &DeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout{}
}

/* DeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout describes a response with status code 504, with default header values.

Gateway timeout
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout struct {
	Payload *models.GatewayTimeout
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout) Error() string {
	return fmt.Sprintf("[DELETE /v1/characters/{character_id}/mail/labels/{label_id}/][%d] deleteCharactersCharacterIdMailLabelsLabelIdGatewayTimeout  %+v", 504, o.Payload)
}
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout) GetPayload() *models.GatewayTimeout {
	return o.Payload
}

func (o *DeleteCharactersCharacterIDMailLabelsLabelIDGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayTimeout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody delete_characters_character_id_mail_labels_label_id_unprocessable_entity
//
// Unprocessable entity
swagger:model DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody
*/
type DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody struct {

	// delete_characters_character_id_mail_labels_label_id_422_unprocessable_entity
	//
	// Unprocessable entity message
	Error string `json:"error,omitempty"`
}

// Validate validates this delete characters character ID mail labels label ID unprocessable entity body
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete characters character ID mail labels label ID unprocessable entity body based on context it is used
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody) UnmarshalBinary(b []byte) error {
	var res DeleteCharactersCharacterIDMailLabelsLabelIDUnprocessableEntityBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
