// Code generated by go-swagger; DO NOT EDIT.

package meta

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHeadersParams creates a new GetHeadersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHeadersParams() *GetHeadersParams {
	return &GetHeadersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHeadersParamsWithTimeout creates a new GetHeadersParams object
// with the ability to set a timeout on a request.
func NewGetHeadersParamsWithTimeout(timeout time.Duration) *GetHeadersParams {
	return &GetHeadersParams{
		timeout: timeout,
	}
}

// NewGetHeadersParamsWithContext creates a new GetHeadersParams object
// with the ability to set a context for a request.
func NewGetHeadersParamsWithContext(ctx context.Context) *GetHeadersParams {
	return &GetHeadersParams{
		Context: ctx,
	}
}

// NewGetHeadersParamsWithHTTPClient creates a new GetHeadersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHeadersParamsWithHTTPClient(client *http.Client) *GetHeadersParams {
	return &GetHeadersParams{
		HTTPClient: client,
	}
}

/* GetHeadersParams contains all the parameters to send to the API endpoint
   for the get headers operation.

   Typically these are written to a http.Request.
*/
type GetHeadersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get headers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeadersParams) WithDefaults() *GetHeadersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get headers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeadersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get headers params
func (o *GetHeadersParams) WithTimeout(timeout time.Duration) *GetHeadersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get headers params
func (o *GetHeadersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get headers params
func (o *GetHeadersParams) WithContext(ctx context.Context) *GetHeadersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get headers params
func (o *GetHeadersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get headers params
func (o *GetHeadersParams) WithHTTPClient(client *http.Client) *GetHeadersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get headers params
func (o *GetHeadersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHeadersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
