// Code generated by go-swagger; DO NOT EDIT.

package universe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/ferocious-space/eveapi/models"
)

// GetUniverseFactionsReader is a Reader for the GetUniverseFactions structure.
type GetUniverseFactionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUniverseFactionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUniverseFactionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewGetUniverseFactionsNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewGetUniverseFactionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 420:
		result := NewGetUniverseFactionsEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetUniverseFactionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetUniverseFactionsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetUniverseFactionsGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUniverseFactionsOK creates a GetUniverseFactionsOK with default headers values
func NewGetUniverseFactionsOK() *GetUniverseFactionsOK {
	return &GetUniverseFactionsOK{}
}

/*
GetUniverseFactionsOK describes a response with status code 200, with default header values.

A list of factions
*/
type GetUniverseFactionsOK struct {

	/* The caching mechanism used
	 */
	CacheControl string

	/* The language used in the response
	 */
	ContentLanguage string

	/* RFC7232 compliant entity tag
	 */
	ETag string

	/* RFC7231 formatted datetime string
	 */
	Expires string

	/* RFC7231 formatted datetime string
	 */
	LastModified string

	Payload []*GetUniverseFactionsOKBodyItems0
}

// IsSuccess returns true when this get universe factions o k response has a 2xx status code
func (o *GetUniverseFactionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get universe factions o k response has a 3xx status code
func (o *GetUniverseFactionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get universe factions o k response has a 4xx status code
func (o *GetUniverseFactionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get universe factions o k response has a 5xx status code
func (o *GetUniverseFactionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get universe factions o k response a status code equal to that given
func (o *GetUniverseFactionsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetUniverseFactionsOK) Error() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsOK  %+v", 200, o.Payload)
}

func (o *GetUniverseFactionsOK) String() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsOK  %+v", 200, o.Payload)
}

func (o *GetUniverseFactionsOK) GetPayload() []*GetUniverseFactionsOKBodyItems0 {
	return o.Payload
}

func (o *GetUniverseFactionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Cache-Control
	hdrCacheControl := response.GetHeader("Cache-Control")

	if hdrCacheControl != "" {
		o.CacheControl = hdrCacheControl
	}

	// hydrates response header Content-Language
	hdrContentLanguage := response.GetHeader("Content-Language")

	if hdrContentLanguage != "" {
		o.ContentLanguage = hdrContentLanguage
	}

	// hydrates response header ETag
	hdrETag := response.GetHeader("ETag")

	if hdrETag != "" {
		o.ETag = hdrETag
	}

	// hydrates response header Expires
	hdrExpires := response.GetHeader("Expires")

	if hdrExpires != "" {
		o.Expires = hdrExpires
	}

	// hydrates response header Last-Modified
	hdrLastModified := response.GetHeader("Last-Modified")

	if hdrLastModified != "" {
		o.LastModified = hdrLastModified
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUniverseFactionsNotModified creates a GetUniverseFactionsNotModified with default headers values
func NewGetUniverseFactionsNotModified() *GetUniverseFactionsNotModified {
	return &GetUniverseFactionsNotModified{}
}

/*
GetUniverseFactionsNotModified describes a response with status code 304, with default header values.

Not modified
*/
type GetUniverseFactionsNotModified struct {

	/* The caching mechanism used
	 */
	CacheControl string

	/* RFC7232 compliant entity tag
	 */
	ETag string

	/* RFC7231 formatted datetime string
	 */
	Expires string

	/* RFC7231 formatted datetime string
	 */
	LastModified string
}

// IsSuccess returns true when this get universe factions not modified response has a 2xx status code
func (o *GetUniverseFactionsNotModified) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get universe factions not modified response has a 3xx status code
func (o *GetUniverseFactionsNotModified) IsRedirect() bool {
	return true
}

// IsClientError returns true when this get universe factions not modified response has a 4xx status code
func (o *GetUniverseFactionsNotModified) IsClientError() bool {
	return false
}

// IsServerError returns true when this get universe factions not modified response has a 5xx status code
func (o *GetUniverseFactionsNotModified) IsServerError() bool {
	return false
}

// IsCode returns true when this get universe factions not modified response a status code equal to that given
func (o *GetUniverseFactionsNotModified) IsCode(code int) bool {
	return code == 304
}

func (o *GetUniverseFactionsNotModified) Error() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsNotModified ", 304)
}

func (o *GetUniverseFactionsNotModified) String() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsNotModified ", 304)
}

func (o *GetUniverseFactionsNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Cache-Control
	hdrCacheControl := response.GetHeader("Cache-Control")

	if hdrCacheControl != "" {
		o.CacheControl = hdrCacheControl
	}

	// hydrates response header ETag
	hdrETag := response.GetHeader("ETag")

	if hdrETag != "" {
		o.ETag = hdrETag
	}

	// hydrates response header Expires
	hdrExpires := response.GetHeader("Expires")

	if hdrExpires != "" {
		o.Expires = hdrExpires
	}

	// hydrates response header Last-Modified
	hdrLastModified := response.GetHeader("Last-Modified")

	if hdrLastModified != "" {
		o.LastModified = hdrLastModified
	}

	return nil
}

// NewGetUniverseFactionsBadRequest creates a GetUniverseFactionsBadRequest with default headers values
func NewGetUniverseFactionsBadRequest() *GetUniverseFactionsBadRequest {
	return &GetUniverseFactionsBadRequest{}
}

/*
GetUniverseFactionsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetUniverseFactionsBadRequest struct {
	Payload *models.BadRequest
}

// IsSuccess returns true when this get universe factions bad request response has a 2xx status code
func (o *GetUniverseFactionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get universe factions bad request response has a 3xx status code
func (o *GetUniverseFactionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get universe factions bad request response has a 4xx status code
func (o *GetUniverseFactionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get universe factions bad request response has a 5xx status code
func (o *GetUniverseFactionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get universe factions bad request response a status code equal to that given
func (o *GetUniverseFactionsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetUniverseFactionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsBadRequest  %+v", 400, o.Payload)
}

func (o *GetUniverseFactionsBadRequest) String() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsBadRequest  %+v", 400, o.Payload)
}

func (o *GetUniverseFactionsBadRequest) GetPayload() *models.BadRequest {
	return o.Payload
}

func (o *GetUniverseFactionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUniverseFactionsEnhanceYourCalm creates a GetUniverseFactionsEnhanceYourCalm with default headers values
func NewGetUniverseFactionsEnhanceYourCalm() *GetUniverseFactionsEnhanceYourCalm {
	return &GetUniverseFactionsEnhanceYourCalm{}
}

/*
GetUniverseFactionsEnhanceYourCalm describes a response with status code 420, with default header values.

Error limited
*/
type GetUniverseFactionsEnhanceYourCalm struct {
	Payload *models.ErrorLimited
}

// IsSuccess returns true when this get universe factions enhance your calm response has a 2xx status code
func (o *GetUniverseFactionsEnhanceYourCalm) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get universe factions enhance your calm response has a 3xx status code
func (o *GetUniverseFactionsEnhanceYourCalm) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get universe factions enhance your calm response has a 4xx status code
func (o *GetUniverseFactionsEnhanceYourCalm) IsClientError() bool {
	return true
}

// IsServerError returns true when this get universe factions enhance your calm response has a 5xx status code
func (o *GetUniverseFactionsEnhanceYourCalm) IsServerError() bool {
	return false
}

// IsCode returns true when this get universe factions enhance your calm response a status code equal to that given
func (o *GetUniverseFactionsEnhanceYourCalm) IsCode(code int) bool {
	return code == 420
}

func (o *GetUniverseFactionsEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *GetUniverseFactionsEnhanceYourCalm) String() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *GetUniverseFactionsEnhanceYourCalm) GetPayload() *models.ErrorLimited {
	return o.Payload
}

func (o *GetUniverseFactionsEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorLimited)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUniverseFactionsInternalServerError creates a GetUniverseFactionsInternalServerError with default headers values
func NewGetUniverseFactionsInternalServerError() *GetUniverseFactionsInternalServerError {
	return &GetUniverseFactionsInternalServerError{}
}

/*
GetUniverseFactionsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetUniverseFactionsInternalServerError struct {
	Payload *models.InternalServerError
}

// IsSuccess returns true when this get universe factions internal server error response has a 2xx status code
func (o *GetUniverseFactionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get universe factions internal server error response has a 3xx status code
func (o *GetUniverseFactionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get universe factions internal server error response has a 4xx status code
func (o *GetUniverseFactionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get universe factions internal server error response has a 5xx status code
func (o *GetUniverseFactionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get universe factions internal server error response a status code equal to that given
func (o *GetUniverseFactionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetUniverseFactionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUniverseFactionsInternalServerError) String() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUniverseFactionsInternalServerError) GetPayload() *models.InternalServerError {
	return o.Payload
}

func (o *GetUniverseFactionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUniverseFactionsServiceUnavailable creates a GetUniverseFactionsServiceUnavailable with default headers values
func NewGetUniverseFactionsServiceUnavailable() *GetUniverseFactionsServiceUnavailable {
	return &GetUniverseFactionsServiceUnavailable{}
}

/*
GetUniverseFactionsServiceUnavailable describes a response with status code 503, with default header values.

Service unavailable
*/
type GetUniverseFactionsServiceUnavailable struct {
	Payload *models.ServiceUnavailable
}

// IsSuccess returns true when this get universe factions service unavailable response has a 2xx status code
func (o *GetUniverseFactionsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get universe factions service unavailable response has a 3xx status code
func (o *GetUniverseFactionsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get universe factions service unavailable response has a 4xx status code
func (o *GetUniverseFactionsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get universe factions service unavailable response has a 5xx status code
func (o *GetUniverseFactionsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get universe factions service unavailable response a status code equal to that given
func (o *GetUniverseFactionsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

func (o *GetUniverseFactionsServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetUniverseFactionsServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetUniverseFactionsServiceUnavailable) GetPayload() *models.ServiceUnavailable {
	return o.Payload
}

func (o *GetUniverseFactionsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUniverseFactionsGatewayTimeout creates a GetUniverseFactionsGatewayTimeout with default headers values
func NewGetUniverseFactionsGatewayTimeout() *GetUniverseFactionsGatewayTimeout {
	return &GetUniverseFactionsGatewayTimeout{}
}

/*
GetUniverseFactionsGatewayTimeout describes a response with status code 504, with default header values.

Gateway timeout
*/
type GetUniverseFactionsGatewayTimeout struct {
	Payload *models.GatewayTimeout
}

// IsSuccess returns true when this get universe factions gateway timeout response has a 2xx status code
func (o *GetUniverseFactionsGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get universe factions gateway timeout response has a 3xx status code
func (o *GetUniverseFactionsGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get universe factions gateway timeout response has a 4xx status code
func (o *GetUniverseFactionsGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this get universe factions gateway timeout response has a 5xx status code
func (o *GetUniverseFactionsGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this get universe factions gateway timeout response a status code equal to that given
func (o *GetUniverseFactionsGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

func (o *GetUniverseFactionsGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetUniverseFactionsGatewayTimeout) String() string {
	return fmt.Sprintf("[GET /v2/universe/factions/][%d] getUniverseFactionsGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetUniverseFactionsGatewayTimeout) GetPayload() *models.GatewayTimeout {
	return o.Payload
}

func (o *GetUniverseFactionsGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayTimeout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetUniverseFactionsOKBodyItems0 get_universe_factions_200_ok
//
// 200 ok object
swagger:model GetUniverseFactionsOKBodyItems0
*/
type GetUniverseFactionsOKBodyItems0 struct {

	// get_universe_factions_corporation_id
	//
	// corporation_id integer
	CorporationID int32 `json:"corporation_id,omitempty"`

	// get_universe_factions_description
	//
	// description string
	// Required: true
	Description *string `json:"description"`

	// get_universe_factions_faction_id
	//
	// faction_id integer
	// Required: true
	FactionID *int32 `json:"faction_id"`

	// get_universe_factions_is_unique
	//
	// is_unique boolean
	// Required: true
	IsUnique *bool `json:"is_unique"`

	// get_universe_factions_militia_corporation_id
	//
	// militia_corporation_id integer
	MilitiaCorporationID int32 `json:"militia_corporation_id,omitempty"`

	// get_universe_factions_name
	//
	// name string
	// Required: true
	Name *string `json:"name"`

	// get_universe_factions_size_factor
	//
	// size_factor number
	// Required: true
	SizeFactor *float32 `json:"size_factor"`

	// get_universe_factions_solar_system_id
	//
	// solar_system_id integer
	SolarSystemID int32 `json:"solar_system_id,omitempty"`

	// get_universe_factions_station_count
	//
	// station_count integer
	// Required: true
	StationCount *int32 `json:"station_count"`

	// get_universe_factions_station_system_count
	//
	// station_system_count integer
	// Required: true
	StationSystemCount *int32 `json:"station_system_count"`
}

// Validate validates this get universe factions o k body items0
func (o *GetUniverseFactionsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFactionID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIsUnique(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSizeFactor(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStationCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStationSystemCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetUniverseFactionsOKBodyItems0) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", o.Description); err != nil {
		return err
	}

	return nil
}

func (o *GetUniverseFactionsOKBodyItems0) validateFactionID(formats strfmt.Registry) error {

	if err := validate.Required("faction_id", "body", o.FactionID); err != nil {
		return err
	}

	return nil
}

func (o *GetUniverseFactionsOKBodyItems0) validateIsUnique(formats strfmt.Registry) error {

	if err := validate.Required("is_unique", "body", o.IsUnique); err != nil {
		return err
	}

	return nil
}

func (o *GetUniverseFactionsOKBodyItems0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

func (o *GetUniverseFactionsOKBodyItems0) validateSizeFactor(formats strfmt.Registry) error {

	if err := validate.Required("size_factor", "body", o.SizeFactor); err != nil {
		return err
	}

	return nil
}

func (o *GetUniverseFactionsOKBodyItems0) validateStationCount(formats strfmt.Registry) error {

	if err := validate.Required("station_count", "body", o.StationCount); err != nil {
		return err
	}

	return nil
}

func (o *GetUniverseFactionsOKBodyItems0) validateStationSystemCount(formats strfmt.Registry) error {

	if err := validate.Required("station_system_count", "body", o.StationSystemCount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get universe factions o k body items0 based on context it is used
func (o *GetUniverseFactionsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUniverseFactionsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUniverseFactionsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetUniverseFactionsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
