// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/ferocious-space/eveapi/models"
)

// GetCharactersCharacterIDContractsContractIDBidsReader is a Reader for the GetCharactersCharacterIDContractsContractIDBids structure.
type GetCharactersCharacterIDContractsContractIDBidsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCharactersCharacterIDContractsContractIDBidsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCharactersCharacterIDContractsContractIDBidsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewGetCharactersCharacterIDContractsContractIDBidsNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewGetCharactersCharacterIDContractsContractIDBidsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetCharactersCharacterIDContractsContractIDBidsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetCharactersCharacterIDContractsContractIDBidsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCharactersCharacterIDContractsContractIDBidsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 420:
		result := NewGetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCharactersCharacterIDContractsContractIDBidsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetCharactersCharacterIDContractsContractIDBidsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetCharactersCharacterIDContractsContractIDBidsGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCharactersCharacterIDContractsContractIDBidsOK creates a GetCharactersCharacterIDContractsContractIDBidsOK with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsOK() *GetCharactersCharacterIDContractsContractIDBidsOK {
	return &GetCharactersCharacterIDContractsContractIDBidsOK{}
}

/* GetCharactersCharacterIDContractsContractIDBidsOK describes a response with status code 200, with default header values.

A list of bids
*/
type GetCharactersCharacterIDContractsContractIDBidsOK struct {

	/* The caching mechanism used
	 */
	CacheControl string

	/* RFC7232 compliant entity tag
	 */
	ETag string

	/* RFC7231 formatted datetime string
	 */
	Expires string

	/* RFC7231 formatted datetime string
	 */
	LastModified string

	Payload []*GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0
}

func (o *GetCharactersCharacterIDContractsContractIDBidsOK) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsOK  %+v", 200, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsOK) GetPayload() []*GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0 {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Cache-Control
	hdrCacheControl := response.GetHeader("Cache-Control")

	if hdrCacheControl != "" {
		o.CacheControl = hdrCacheControl
	}

	// hydrates response header ETag
	hdrETag := response.GetHeader("ETag")

	if hdrETag != "" {
		o.ETag = hdrETag
	}

	// hydrates response header Expires
	hdrExpires := response.GetHeader("Expires")

	if hdrExpires != "" {
		o.Expires = hdrExpires
	}

	// hydrates response header Last-Modified
	hdrLastModified := response.GetHeader("Last-Modified")

	if hdrLastModified != "" {
		o.LastModified = hdrLastModified
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsNotModified creates a GetCharactersCharacterIDContractsContractIDBidsNotModified with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsNotModified() *GetCharactersCharacterIDContractsContractIDBidsNotModified {
	return &GetCharactersCharacterIDContractsContractIDBidsNotModified{}
}

/* GetCharactersCharacterIDContractsContractIDBidsNotModified describes a response with status code 304, with default header values.

Not modified
*/
type GetCharactersCharacterIDContractsContractIDBidsNotModified struct {

	/* The caching mechanism used
	 */
	CacheControl string

	/* RFC7232 compliant entity tag
	 */
	ETag string

	/* RFC7231 formatted datetime string
	 */
	Expires string

	/* RFC7231 formatted datetime string
	 */
	LastModified string
}

func (o *GetCharactersCharacterIDContractsContractIDBidsNotModified) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsNotModified ", 304)
}

func (o *GetCharactersCharacterIDContractsContractIDBidsNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Cache-Control
	hdrCacheControl := response.GetHeader("Cache-Control")

	if hdrCacheControl != "" {
		o.CacheControl = hdrCacheControl
	}

	// hydrates response header ETag
	hdrETag := response.GetHeader("ETag")

	if hdrETag != "" {
		o.ETag = hdrETag
	}

	// hydrates response header Expires
	hdrExpires := response.GetHeader("Expires")

	if hdrExpires != "" {
		o.Expires = hdrExpires
	}

	// hydrates response header Last-Modified
	hdrLastModified := response.GetHeader("Last-Modified")

	if hdrLastModified != "" {
		o.LastModified = hdrLastModified
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsBadRequest creates a GetCharactersCharacterIDContractsContractIDBidsBadRequest with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsBadRequest() *GetCharactersCharacterIDContractsContractIDBidsBadRequest {
	return &GetCharactersCharacterIDContractsContractIDBidsBadRequest{}
}

/* GetCharactersCharacterIDContractsContractIDBidsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetCharactersCharacterIDContractsContractIDBidsBadRequest struct {
	Payload *models.BadRequest
}

func (o *GetCharactersCharacterIDContractsContractIDBidsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsBadRequest  %+v", 400, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsBadRequest) GetPayload() *models.BadRequest {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsUnauthorized creates a GetCharactersCharacterIDContractsContractIDBidsUnauthorized with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsUnauthorized() *GetCharactersCharacterIDContractsContractIDBidsUnauthorized {
	return &GetCharactersCharacterIDContractsContractIDBidsUnauthorized{}
}

/* GetCharactersCharacterIDContractsContractIDBidsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetCharactersCharacterIDContractsContractIDBidsUnauthorized struct {
	Payload *models.Unauthorized
}

func (o *GetCharactersCharacterIDContractsContractIDBidsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsForbidden creates a GetCharactersCharacterIDContractsContractIDBidsForbidden with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsForbidden() *GetCharactersCharacterIDContractsContractIDBidsForbidden {
	return &GetCharactersCharacterIDContractsContractIDBidsForbidden{}
}

/* GetCharactersCharacterIDContractsContractIDBidsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetCharactersCharacterIDContractsContractIDBidsForbidden struct {
	Payload *models.Forbidden
}

func (o *GetCharactersCharacterIDContractsContractIDBidsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsForbidden  %+v", 403, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsNotFound creates a GetCharactersCharacterIDContractsContractIDBidsNotFound with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsNotFound() *GetCharactersCharacterIDContractsContractIDBidsNotFound {
	return &GetCharactersCharacterIDContractsContractIDBidsNotFound{}
}

/* GetCharactersCharacterIDContractsContractIDBidsNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetCharactersCharacterIDContractsContractIDBidsNotFound struct {
	Payload *GetCharactersCharacterIDContractsContractIDBidsNotFoundBody
}

func (o *GetCharactersCharacterIDContractsContractIDBidsNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsNotFound  %+v", 404, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsNotFound) GetPayload() *GetCharactersCharacterIDContractsContractIDBidsNotFoundBody {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCharactersCharacterIDContractsContractIDBidsNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm creates a GetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm() *GetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm {
	return &GetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm{}
}

/* GetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm describes a response with status code 420, with default header values.

Error limited
*/
type GetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm struct {
	Payload *models.ErrorLimited
}

func (o *GetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsEnhanceYourCalm  %+v", 420, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm) GetPayload() *models.ErrorLimited {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorLimited)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsInternalServerError creates a GetCharactersCharacterIDContractsContractIDBidsInternalServerError with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsInternalServerError() *GetCharactersCharacterIDContractsContractIDBidsInternalServerError {
	return &GetCharactersCharacterIDContractsContractIDBidsInternalServerError{}
}

/* GetCharactersCharacterIDContractsContractIDBidsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetCharactersCharacterIDContractsContractIDBidsInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *GetCharactersCharacterIDContractsContractIDBidsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsInternalServerError) GetPayload() *models.InternalServerError {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsServiceUnavailable creates a GetCharactersCharacterIDContractsContractIDBidsServiceUnavailable with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsServiceUnavailable() *GetCharactersCharacterIDContractsContractIDBidsServiceUnavailable {
	return &GetCharactersCharacterIDContractsContractIDBidsServiceUnavailable{}
}

/* GetCharactersCharacterIDContractsContractIDBidsServiceUnavailable describes a response with status code 503, with default header values.

Service unavailable
*/
type GetCharactersCharacterIDContractsContractIDBidsServiceUnavailable struct {
	Payload *models.ServiceUnavailable
}

func (o *GetCharactersCharacterIDContractsContractIDBidsServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsServiceUnavailable  %+v", 503, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsServiceUnavailable) GetPayload() *models.ServiceUnavailable {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDContractsContractIDBidsGatewayTimeout creates a GetCharactersCharacterIDContractsContractIDBidsGatewayTimeout with default headers values
func NewGetCharactersCharacterIDContractsContractIDBidsGatewayTimeout() *GetCharactersCharacterIDContractsContractIDBidsGatewayTimeout {
	return &GetCharactersCharacterIDContractsContractIDBidsGatewayTimeout{}
}

/* GetCharactersCharacterIDContractsContractIDBidsGatewayTimeout describes a response with status code 504, with default header values.

Gateway timeout
*/
type GetCharactersCharacterIDContractsContractIDBidsGatewayTimeout struct {
	Payload *models.GatewayTimeout
}

func (o *GetCharactersCharacterIDContractsContractIDBidsGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/characters/{character_id}/contracts/{contract_id}/bids/][%d] getCharactersCharacterIdContractsContractIdBidsGatewayTimeout  %+v", 504, o.Payload)
}
func (o *GetCharactersCharacterIDContractsContractIDBidsGatewayTimeout) GetPayload() *models.GatewayTimeout {
	return o.Payload
}

func (o *GetCharactersCharacterIDContractsContractIDBidsGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayTimeout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetCharactersCharacterIDContractsContractIDBidsNotFoundBody get_characters_character_id_contracts_contract_id_bids_not_found
//
// Not found
swagger:model GetCharactersCharacterIDContractsContractIDBidsNotFoundBody
*/
type GetCharactersCharacterIDContractsContractIDBidsNotFoundBody struct {

	// get_characters_character_id_contracts_contract_id_bids_404_not_found
	//
	// Not found message
	Error string `json:"error,omitempty"`
}

// Validate validates this get characters character ID contracts contract ID bids not found body
func (o *GetCharactersCharacterIDContractsContractIDBidsNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get characters character ID contracts contract ID bids not found body based on context it is used
func (o *GetCharactersCharacterIDContractsContractIDBidsNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDContractsContractIDBidsNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDContractsContractIDBidsNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDContractsContractIDBidsNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0 get_characters_character_id_contracts_contract_id_bids_200_ok
//
// 200 ok object
swagger:model GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0
*/
type GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0 struct {

	// get_characters_character_id_contracts_contract_id_bids_amount
	//
	// The amount bid, in ISK
	// Required: true
	Amount *float32 `json:"amount"`

	// get_characters_character_id_contracts_contract_id_bids_bid_id
	//
	// Unique ID for the bid
	// Required: true
	BidID *int32 `json:"bid_id"`

	// get_characters_character_id_contracts_contract_id_bids_bidder_id
	//
	// Character ID of the bidder
	// Required: true
	BidderID *int32 `json:"bidder_id"`

	// get_characters_character_id_contracts_contract_id_bids_date_bid
	//
	// Datetime when the bid was placed
	// Required: true
	// Format: date-time
	DateBid *strfmt.DateTime `json:"date_bid"`
}

// Validate validates this get characters character ID contracts contract ID bids o k body items0
func (o *GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBidID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBidderID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDateBid(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", o.Amount); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0) validateBidID(formats strfmt.Registry) error {

	if err := validate.Required("bid_id", "body", o.BidID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0) validateBidderID(formats strfmt.Registry) error {

	if err := validate.Required("bidder_id", "body", o.BidderID); err != nil {
		return err
	}

	return nil
}

func (o *GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0) validateDateBid(formats strfmt.Registry) error {

	if err := validate.Required("date_bid", "body", o.DateBid); err != nil {
		return err
	}

	if err := validate.FormatOf("date_bid", "body", "date-time", o.DateBid.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get characters character ID contracts contract ID bids o k body items0 based on context it is used
func (o *GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDContractsContractIDBidsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
